name: tdd_reso
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^2.0.3
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  dartz: ^0.8.7
  connectivity: ^0.4.4
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true
